# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pyxiong/FPGA_Project/Shift_Register/Shift_Register.cache/wt [current_project]
set_property parent.project_path /home/pyxiong/FPGA_Project/Shift_Register/Shift_Register.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/pyxiong/FPGA_Project/Shift_Register/Shift_Register.srcs/sources_1/new/SR_Control.v
  /home/pyxiong/FPGA_Project/Shift_Register/Shift_Register.srcs/sources_1/new/Recieve_Data.v
  /home/pyxiong/FPGA_Project/Shift_Register/Shift_Register.srcs/sources_1/new/Clock_Div.v
  /home/pyxiong/FPGA_Project/Shift_Register/Shift_Register.srcs/sources_1/new/Top_SR.v
}
synth_design -top Top_SR -part xcku040-ffva1156-2-e
write_checkpoint -noxdef Top_SR.dcp
catch { report_utilization -file Top_SR_utilization_synth.rpt -pb Top_SR_utilization_synth.pb }
